version: '2'
services:
  solr:
    image: solr
    ports:
     - "8983:8983"
    volumes:
      - data:/opt/solr/server/solr/mycores
      - ./data:/var/data
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - pinboard
  web:
    build: ./web
    ports:
      - "5000:5000"
    volumes:
      - ./web:/app
    links:
      - solr
volumes:
  data:
